version: "3.2"

services:
  web:
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/index.html:/usr/local/apache2/htdocs/index.html
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./ssl-keys/server.key:/usr/local/apache2/conf/server.key
      - ./ssl-keys/server.crt:/usr/local/apache2/conf/server.crt

